### PR TITLE
update the template to support the new full site edit

### PR DESCRIPTION
**Pull request by erikyo**

### CODE REVIEW

**Comment by johnhooks** [comment]
No problem! I'm glad the configs are helpful... though I really wish there didn't have to be so many of them. Not a judgement of your project, but of the JS ecosystem.

**Comment by erikyo** [comment]
> No problem! I'm glad the configs are helpful... though I really wish there didn't have to be so many of them. Not a judgement of your project, but of the JS ecosystem.

Fortunately, with the 'release' command I found a way to make a zip file of the theme with only the necessary files and folders... but yep it's quite tedious and I almost struggle to find a file in the root when i need it 😅

**Comment by johnhooks** [comment]
I've heard most of them can be thrown into a `.config` directory in the project root. I should try it.

**Comment by johnhooks** [comment]
That config makes sense to me. As written, it works as long as eslint and typescript are configured to check and lint `.js` files. Otherwise `overrides` should be used in the `.eslintrc`.

**Pull request merged**
